# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ee7be9052859bd815bffe1752a3402a1fc85115ab204ae557860b01fa0d7061caf51504a988dc6b073dc4418595322a66b7ccf9a313d63153bbe07473546372c

test:
  secret_key_base: 757d1ac80e4d7cb68135126404bc6be01fdab63707564317b26a759f3fc0decaf7ed7e51273ae90fa701186fef44a6062b0953bc759da444e205417c6f937d9d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
